apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: test-clu-aks-provider-helm-pc
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: krateo-system
      name: azure-account-creds-secret
      key: credentials
