apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: aks-template
spec:
  owner: simone.ragonesi@kiratech.it
  title: AKS
  description: Krateo AKS Template
  icon: fa-brands fa-microsoft
  tags:
    - aks
  widgets:
    - title: Name and description
      description: Name and description of the stack.
      properties:
        - title: Name
          description: The name of the component
          required: true
          key: name
        - title: Description
          key: description
          description: Help others understand what this deployment does.
          required: true
          default: AKS Stack sample
        - title: Namespace
          key: namespace
          description: Krateo namespace for the stack.
          required: true
          default: krateo-system
    - title: Kubernetes
      box: Kubernetes cluster name and network name.
      boxStyle: info
      properties:
        - key: clusterId
          title: Cluster ID
          description: The ID of the cluster
          required: true
        - key: location
          title: Cluster location
          description: Cluster location (azure zone)
          required: true
          default: westeurope
        - key: clusterVersion
          title: Kubernetes version
          description: Kubernetes version
          required: true
          default: "1.24.3"
        - key: clusterNodes
          title: Cluster Nodes
          description: The number of nodes in the cluster
          required: true
          type: string
          default: "3"
        - key: nodeSize
          title: node vm size
          description: The azure VM size for cluster nodes
          required: true
          default: Standard_D4s_v3
    - title: Vault
      properties:
        - key: vaultVersion
          title: vault version
          description: helm chart version of hashicorp vault
          required: true
          default: "0.22.1"
