apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aksstack.deployment.krateo.io
spec:
  compositeTypeRef:
    apiVersion: deployment.krateo.io/v1alpha1
    kind: AksStack
  resources:
    #- base:
    #apiVersion: azure.aksstack.upbound.io/v1alpha1
    #kind: XNetwork
    #patches:
    #- fromFieldPath: spec.id
    #toFieldPath: spec.id
    - base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: krateo-system
              name: azure-account-creds-secret
              key: credentials
    - base:
        apiVersion: azure.aksstack.upbound.io/v1alpha1
        kind: XAKS
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
      resources:
        - base:
            apiVersion: containerservice.azure.upbound.io/v1beta1
            kind: KubernetesCluster
            spec:
              forProvider:
                resourceGroupName: test-rg # patched
                location: westeurope # patched
                kubernetesVersion: "1.24.3" # patched
                defaultNodePool:
                  - name: default
                    nodeCount: 1 # patched
                    vmSize: Standard_D4s_v3 # patched
                identity:
                  - type: "SystemAssigned"
      patches:
        - fromFieldPath: spec.values.id
          toFieldPath: spec.forProvider.vnetSubnetIdSelector.matchLabels[azure.aksstack.upbound.io/app]
        - fromFieldPath: spec.values.id
          toFieldPath: spec.forProvider.dnsPrefix
        - fromFieldPath: spec.values.location
          toFieldPath: spec.forProvider.location
        # - fromFieldPath: spec.values.resourceGroup
        #   toFieldPath: spec.forProvider.resourceGroupName
        - fromFieldPath: spec.values.clusterVersion
          toFieldPath: spec.forProvider.kubernetesVersion
        - fromFieldPath: spec.values.clusterVersion
          toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
        - fromFieldPath: spec.values.clusterNodes
          toFieldPath: spec.forProvider.defaultNodePool[0].nodeCount
        - fromFieldPath: spec.values.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.values.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-aks"
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              key: kubeconfig
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.values.namespace
          toFieldPath: spec.credentials.secretRef.namespace
        # This ProviderConfig uses the above AKS cluster's connection secret as
        # its credentials secret.
        - fromFieldPath: spec.values.name
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-aks"
      readinessChecks:
        - type: None
    #- base:
    #apiVersion: azure.aksstack.upbound.io/v1alpha1
    #kind: XKeptnServices
    #patches:
    #- fromFieldPath: spec.id
    #toFieldPath: metadata.name
    #- fromFieldPath: spec.id
    #toFieldPath: spec.providerConfigRef.name
    #- fromFieldPath: spec.parameters.keptnservices.operators.keptn.version
    #toFieldPath: spec.operators.keptn.version
    #- base:
    #apiVersion: azure.aksstack.upbound.io/v1alpha1
    #kind: XElasticsearchServices
    #patches:
    #- fromFieldPath: spec.id
    #toFieldPath: metadata.name
    #- fromFieldPath: spec.id
    #toFieldPath: spec.providerConfigRef.name
    #- fromFieldPath: spec.parameters.elasticsearchservices.operators.elasticsearch.version
    #toFieldPath: spec.operators.elasticsearch.version
