apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aksstack.deployment.krateo.io
spec:
  compositeTypeRef:
    apiVersion: deployment.krateo.io/v1alpha1
    kind: AksStack
  resources:
    #- base:
        #apiVersion: azure.aksstack.upbound.io/v1alpha1
        #kind: XNetwork
      #patches:
        #- fromFieldPath: spec.id
          #toFieldPath: spec.id
    - base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: krateo-system
              name: azure-account-creds-secret
              key: credentials
    - base:
        apiVersion: azure.aksstack.upbound.io/v1alpha1
        kind: XAKS
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
      resources:
      - base:
          apiVersion: containerservice.azure.upbound.io/v1beta1
          kind: KubernetesCluster
          spec:
            forProvider:
              resourceGroupName: test-rg # patched
              location: westeurope # patched
              kubernetesVersion: "1.24.3" # patched
              defaultNodePool:
                - name: default
                  nodeCount: 1 # patched
                  vmSize: Standard_D4s_v3 # patched
              identity:
                - type: "SystemAssigned"
      patches:
        - fromFieldPath: spec.values.id
          toFieldPath: spec.id
        - fromFieldPath: spec.values.id
          toFieldPath: spec.writeConnectionSecretToRef.name
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.values.location
          toFieldPath: spec.parameters.location
        - fromFieldPath: spec.parameters.resourceGroup
          toFieldPath: spec.parameters.resourceGroup
        - fromFieldPath: spec.values.clusterVersion
          toFieldPath: spec.parameters.kubernetesVersion
        - fromFieldPath: spec.values.clusterNodes
          toFieldPath: spec.parameters.nodes.count
        - fromFieldPath: spec.values.nodeSize
          toFieldPath: spec.parameters.nodes.size
    - base:
        apiVersion: azure.aksstack.upbound.io/v1alpha1
        kind: XVaultServices
      patches:
        - fromFieldPath: spec.values.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.values.id
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.values.vaultVersion
          toFieldPath: spec.operators.vault.version
    #- base:
        #apiVersion: azure.aksstack.upbound.io/v1alpha1
        #kind: XKeptnServices
      #patches:
        #- fromFieldPath: spec.id
          #toFieldPath: metadata.name
        #- fromFieldPath: spec.id
          #toFieldPath: spec.providerConfigRef.name
        #- fromFieldPath: spec.parameters.keptnservices.operators.keptn.version
          #toFieldPath: spec.operators.keptn.version
    #- base:
        #apiVersion: azure.aksstack.upbound.io/v1alpha1
        #kind: XElasticsearchServices
      #patches:
        #- fromFieldPath: spec.id
          #toFieldPath: metadata.name
        #- fromFieldPath: spec.id
          #toFieldPath: spec.providerConfigRef.name
        #- fromFieldPath: spec.parameters.elasticsearchservices.operators.elasticsearch.version
          #toFieldPath: spec.operators.elasticsearch.version
