---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: aksstack.deployment.krateo.io
  labels:
    platform: azure
spec:
  group: deployment.krateo.io
  names:
    kind: AksStack
    plural: aksstack
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                owner:
                  type: string
                title:
                  type: string
                description:
                  type: string
                icon:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                links:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                      title:
                        type: string
                      icon:
                        type: string
                plugins:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      values:
                        type: array
                        items:
                          type: string
                      type:
                        type: string
                      icon:
                        type: string
                      endpointName:
                        type: string
                values:
                  type: object
                  description: Aks Stack deployment values
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    namespace:
                      type: string
                    id:
                      type: string
                    location:
                      type: string
                    clusterVersion:
                      type: string
                    clusterNodes:
                      type: string
                    nodeSize:
                      type: string
                    vaultVersion:
                      type: string
