apiVersion: deployment.krateo.io/v1alpha1
kind: AksStack
metadata:
  name: azure-aks-stack-poc
  namespace: default
  annotations:
    uptest.upbound.io/post-assert-hook: testhooks/delete-release.sh
spec:
  values:
    name: azure-aks-stack
    description: azure-aks-stack
    namespace: krateo-system
    id: azure-aks-stack
    location: westeurope
    clusterVersion: "1.24.3"
    clusterNodes: "3"
    nodeSize: Standard_D4s_v3
    vaultVersion: "0.22.1"
  #writeConnectionSecretToRef:
    #name: azure-aks-stack-kubeconfig #Must be unique for each instance
